# Generated by Django 4.2.8 on 2023-12-19 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versity_id', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Meal_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('quintity', models.PositiveIntegerField(default=1)),
                ('received', models.BooleanField(default=False)),
                ('h_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_control.consumer_user')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_control.daily_meal')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_control.consumer_user')),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
